version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Mirantis/sriov-scheduler
    steps:
      - checkout
      - run: make test
      - setup_remote_docker
      - run: make docker
      - run:
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y socat
            utils/portforward.sh start
            utils/portforward.sh 8080&
            ./utils/build_dind.sh
            make import
            make run-e2e
