version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Mirantis/sriov-scheduler
    steps:
      - checkout
      - run: make test
      - setup_remote_docker
      - run: make docker
      - run: ./utils/build_dind.sh
      - run: make import
