apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sriov-discovery
  namespace: kube-system
  labels:
    app: sriov-scheduler-extender
spec:
  template:
    metadata:
      labels:
        name: sriov-discovery
    spec:
      hostNetwork: true
      containers:
        - name: sriov-discovery
          securityContext:
            privileged: true
          image: yashulyak/sriov-scheduler-extender
          imagePullPolicy: IfNotPresent
          command: ["discovery"]
          volumeMounts:
            - name: sys
              mountPath: /sys
      volumes:
        - name: sys
          hostPath:
              path: /sys
