apiVersion: v1
kind: Service
metadata:
  name: sriov-scheduler-extender
  namespace: kube-system
  labels:
    app: sriov-scheduler-extender
spec:
  type: NodePort
  ports:
  - port: 8989
    targetPort: 8989
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: sriov-scheduler-extender
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sriov-scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sriov-scheduler-extender
    spec:
      containers:
      - name: sriov-scheduler-extender
        image: yashulyak/sriov-scheduler-extender
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
